### ISSUE TITLE
common beanutils和 common-collections jar内部class重复，编译出错

### ISSUE THREAD

**Issue by windsad** [tencentyun/image-java-sdk-v2.0#1]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/collections/Buffer;

common beanutils和 common-collections 两个jar内部class重复，导致编译不过，这问题要怎么解决？

**Comment by fantouch** [comment]
根据 README.md 说明, 用 gradle 引用试试
