### ISSUE TITLE
身份证识别返回的AdvancedInfo中base64串不可用

### ISSUE THREAD

**Issue by belieffaith** [tencentyun/image-java-sdk-v2.0#19]
如图，身份证照片识别后返回advanceInfo，IDCard字段值为base64串的身份证照片，但是为什么拿里边的串转图片失败？有什么限制吗
![image](https://user-images.githubusercontent.com/49670851/60952814-88c5d380-a32e-11e9-864b-b16a62faebe9.png)

**Comment by fantouch** [comment]
转码代码是怎样的? 有什么报错信息吗? 方便贴一下完整的base64吗?
