### ISSUE TITLE
通过视频对比指定身份信息接口 报异常ContentTooLongException

### ISSUE THREAD

**Issue by hellomaybe** [tencentyun/image-java-sdk-v2.0#3]
FaceIdCardLiveDetectFourRequest liveDetectReq = new FaceIdCardLiveDetectFourRequest(bucketName, validate, video, liveDetectIdcardNumber, liveDetectIdcardName, seq);
ret = imageClient.faceIdCardLiveDetectFour(liveDetectReq);

Exception:org.apache.http.ContentTooLongException: Content length is too long: 2277591"}

调用这个方法报一下异常。如何解决

**Comment by fantouch** [comment]
已解决，请 update 代码
