### ISSUE TITLE
android使用报错

### ISSUE THREAD

**Issue by jonenet** [tencentyun/image-java-sdk-v2.0#6]
android studio 中 使用车牌号码识别报错
java.lang.NoSuchFieldError: org.apache.http.conn.ssl.AllowAllHostnameVerifier.INSTANCE

**Comment by jonenet** [comment]
是否此jar包无法在android studio中使用，调用CommonCodecUtils 中的Base64加密encodeBase64String方法找不到，直接调用api：http://recognition.image.myqcloud.com/ocr/plate" 返回错误码3"

**Comment by fantouch** [comment]
已发布新版v2.2.1，兼容Android，谢谢反馈。
